-- MySQL Script generated by MySQL Workbench
-- Sun Jun 20 17:20:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jamproject
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jamproject` ;

-- -----------------------------------------------------
-- Schema jamproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jamproject` DEFAULT CHARACTER SET utf8 ;
USE `jamproject` ;

-- -----------------------------------------------------
-- Table `jamproject`.`activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamproject`.`activities` ;

CREATE TABLE IF NOT EXISTS `jamproject`.`activities` (
  `act_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `act_name` VARCHAR(30) NOT NULL,
  `act_description` TEXT NOT NULL,
  `act_price` DECIMAL(4,2) NOT NULL,
  `act_img` MEDIUMBLOB NULL DEFAULT NULL,
  `act_content` LONGTEXT NOT NULL,
  PRIMARY KEY (`act_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jamproject`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamproject`.`users` ;

CREATE TABLE IF NOT EXISTS `jamproject`.`users` (
  `usr_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `usr_mail` VARCHAR(255) NOT NULL,
  `usr_pass` VARCHAR(255) NOT NULL,
  `usr_fname` VARCHAR(30) NULL DEFAULT NULL,
  `usr_lname` VARCHAR(30) NULL DEFAULT NULL,
  `usr_address` VARCHAR(50) NULL DEFAULT NULL,
  `usr_zipcode` VARCHAR(10) NULL DEFAULT NULL,
  `usr_city` VARCHAR(50) NULL DEFAULT NULL,
  `usr_img` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`usr_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jamproject`.`users_activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamproject`.`users_activities` ;

CREATE TABLE IF NOT EXISTS `jamproject`.`users_activities` (
  `users_usr_id` BIGINT(20) NOT NULL,
  `activities_act_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`users_usr_id`, `activities_act_id`),
  CONSTRAINT `fk_users_has_activities_users`
    FOREIGN KEY (`users_usr_id`)
    REFERENCES `jamproject`.`users` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_activities_activities1`
    FOREIGN KEY (`activities_act_id`)
    REFERENCES `jamproject`.`activities` (`act_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
