-- MySQL Script generated by MySQL Workbench
-- Sun Jun 20 17:20:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jamproject
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jamproject` ;

-- -----------------------------------------------------
-- Schema jamproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jamproject` DEFAULT CHARACTER SET utf8 ;
USE `jamproject` ;

-- -----------------------------------------------------
-- Table `jamproject`.`act`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamproject`.`act` ;

CREATE TABLE IF NOT EXISTS `jamproject`.`act` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `description` TEXT NOT NULL,
  `price` DECIMAL(4,2) NOT NULL,
  `logo` MEDIUMBLOB NULL DEFAULT NULL,
  `content` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jamproject`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamproject`.`usr` ;

CREATE TABLE IF NOT EXISTS `jamproject`.`usr` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(255) NOT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `fname` VARCHAR(30) NULL DEFAULT NULL,
  `lname` VARCHAR(30) NULL DEFAULT NULL,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  `zipcode` VARCHAR(10) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `img` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `jamproject`.`users_activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jamproject`.`usr_act` ;

CREATE TABLE IF NOT EXISTS `jamproject`.`usr_act` (
  `usr_id` BIGINT(20) NOT NULL,
  `act_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`usr_id`, `act_id`),
  CONSTRAINT `fk_usr_act_usr`
    FOREIGN KEY (`usr_id`)
    REFERENCES `jamproject`.`usr` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usr_act_act`
    FOREIGN KEY (`act_id`)
    REFERENCES `jamproject`.`act` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
